### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by liam-middlebrook** [ssternklar/SSMS#1]
First, the standard disclaimer: I am not a lawyer, and this does not constitute legal or financial advice.

Generally, IMHO, it is a good idea to use FSF or OSI Approved Licenses (which can be found here https://www.gnu.org/licenses/licenses.html and here http://opensource.org/licenses/category)

The Free Software Foundation has a useful guide for choosing a license: https://www.gnu.org/licenses/license-recommendations.html

I often reference the Software Freedom Law Center's Legal Primer for both practical and academic purposes (highly recommended): https://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-60002.2

https://tldrlegal.com/ is quite a useful resource for comparing the various FOSS licenses out there once you have some context

To get ahold of actual lawyers/advisors who help FOSS projects, you can reach out to the FSF, SFLC, and OSI at:
licensing@fsf.org
help@softwarefreedom.org
license-discuss@opensource.org

Hope this helps, and happy hacking!

**Comment by ssternklar** [comment]
Due to the fact that this is going to be used for a couple of things that I'm not going to discuss at the moment, I'm not actually sure how I should license this. Assuming everything goes well, this will be released under the MIT licence, but until then anyone wishing to use this code in any way simply must contact me and I will grant a non-exclusive licence to use, modify, redistribute, publish, sublicense, and/or sell copies of it. I'm leaving this issue open to remind me to look into it.

**Comment by Honeybunch** [comment]
I suggest applying a license ASAP. I recommend MIT but a different license might fit your needs better. I will second http://tldrlegal.com as a resource for researching which license is right for you.

**Comment by ssternklar** [comment]
I knew I was going to forget to do this. Now using the MIT License.
